# .streamlit/secrets.toml
GROQ_API_KEY = "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"
SUPABASE_URL = "https://qmnwjusineizolrpmcxq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbndqdXNpbmVpem9scnBtY3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODIwMzEsImV4cCI6MjA2OTM1ODAzMX0.H4c-2fpB2a-UyB1RrnsQQjtvx8JXB94ps-C2KuF9vm4"